version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=***REMOVED***

  inventory_management:
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=***REMOVED***